### ISSUE TITLE
QScroller moves up multiple times after click on option on mobile

### ISSUE THREAD

**Issue by pdanpdan** [quasarframework/app-extension-qscroller#3]
Hi.
On mobile (Android Chrome was used for testing - no iPhone available), on the demo page, on the first QScroller (blue), after you click on an option (try one that is towards bottom, but it happens on almost all):
- the option is selected
- after a short delay the selection is moved one up
- the move up may happen once or multiple times

It looks like it's related to the normal height of items, because I cannot reproduce it in dense mode.

**Comment by hawkeye64** [comment]
Thanks for reporting this. I'll look into it.

**Comment by hawkeye64** [comment]
Ok, so what I see happening is something is selected, it moves into position, then the one above it (on most occassions) gets selected and then that one moves into position. I also do not see this behavior in `dense` mode.

**Comment by hawkeye64** [comment]
@pdanpdan I thnk I have fixed this. Can you verify this is not happening for you?
https://quasarframework.github.io/app-extension-qscroller/demo

**Comment by pdanpdan** [comment]
Looks good. Cannot reproduce it anymore.
Just to check - the initial value is Elephant in the model?

**Comment by hawkeye64** [comment]
Yes, that's the initial value. Thanks for checking it out @pdanpdan, I appreciate it. :)

**Comment by mclate** [comment]
I still see this happening on mobile (on demo page). Happens for all components and for all fields - jumps to one item above.

**Comment by hawkeye64** [comment]
@mclate 
QScroller is currently getting a full rewrite - hopefully to be released sometime next week. Thanks for the patience.
